# -- Basic Settings ------------------------------------------
set -g prefix C-a
set -g escape-time 0
set -g history-limit 50000
set -g mouse on
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

# Set parent terminal title to reflect current window in tmux session
set -g set-titles on
set -g set-titles-string "#I:#W"

# Start index of window/pane with 1
set -g base-index 1
setw -g pane-base-index 1

# -- Key Bindings --------------------------------------------

# Reload tmux configuration
bind C-r source-file ~/.tmux.conf \; display "Config reloaded"

# -- Copy Mode -----------------------------------------------

# Prefer vi style key table
setw -g mode-keys vi

# Scroll up/down by 1 line, half screen, whole screen
bind -T copy-mode-vi M-Up              send-keys -X scroll-up
bind -T copy-mode-vi M-Down            send-keys -X scroll-down
bind -T copy-mode-vi M-PageUp          send-keys -X halfpage-up
bind -T copy-mode-vi M-PageDown        send-keys -X halfpage-down
bind -T copy-mode-vi PageDown          send-keys -X page-down
bind -T copy-mode-vi PageUp            send-keys -X page-up

# When scrolling with mouse wheel, reduce rows per tick to 2 (default is 5)
bind -T copy-mode-vi WheelUpPane       select-pane \; send-keys -X -N 2 scroll-up
bind -T copy-mode-vi WheelDownPane     select-pane \; send-keys -X -N 2 scroll-down

# -- Plugins -------------------------------------------------

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'wfxr/tmux-power'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

set -g @tmux_power_theme 'everforest'
# set -g @tmux_power_show_user false
# set -g @tmux_power_show_host false

set -g @tmux_power_date_icon           ' '
set -g @tmux_power_time_icon           ' '
set -g @tmux_power_user_icon           ' '
set -g @tmux_power_session_icon        ' '

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

