# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

enable_passive: true
passive_key: CTRL

toggle_key: OFF
show_notifications: false
show_icon: false
