name: dates
parent: default

matches: 
  - trigger: ";now"
    replace: "*({{now}})*"
    vars:
      - name: now
        type: date
        params:
          format: "%H:%M"

  - trigger: ";date"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ";ddate"
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%A, %B %e, %Y"

  - trigger: ";yes"
    replace: "{{yesterday}}"
    vars: 
      - name: yesterday
        type: shell
        params: 
          cmd: "date -v-1d +%Y-%m-%d"

  - trigger: ";tom"
    replace: "{{tomorrow}}"
    vars: 
      - name: tomorrow
        type: shell
        params: 
          cmd: "date -v+1d +%Y-%m-%d"

  - trigger: ";ww"
    replace: "{{week}}"
    vars:
      - name: week
        type: date
        params:
          format: "%Y::W%W"
