name: roam
parent: default

matches: 
  - trigger: ";rw"
    replace: |
      ## Overview
      ### Morning Pages

      ### Discovered

      ### Thoughts

      ## Review
      ### What were some of this weeks highlights?

      ### Where did you spend a lot of your emotional and physical resources?

      ### What surprised you this week?

  - trigger: ";today"
    force_clipboard: true
    replace: |
      [[Morning Pages]]

      #Yapp
      
      Discovered::

      Thoughts::

  - trigger: ";month"
    force_clipboard: true
    replace: |
      - Goals::
      - People I want to keep top of mind
      - Books I'd like to read
      - **Dates**

  - trigger: ";scripture"
    force_clipboard: true
    replace: |
      ---

      ---
      #Scripture
      Themes:
      Interpretation:
      Passage:

  - trigger: ";book"
    force_clipboard: true
    replace: |
      ---
      url: 
      tags: []
      ---
      Author:
      Status: #to-read
      Recommended By::
      Highlights::

  - trigger: ";content"
    force_clipboard: true
    replace: |
      ---
      url: []
      tags: []
      ---

  - trigger: ";person"
    replace: |
      ---
      aliases: []
      ---
      #Person

      # $|$