name: yapp
parent: default

matches:
  - trigger: "yyui"
    replace: "ui-elements"

  - trigger: "yyc"
    replace: "yapp-core"

  - trigger: "yys"
    replace: "yapp-server"

  - trigger: "yyed"
    replace: "editor"

  - trigger: "yyd"
    replace: "dashboard"

  - trigger: "yya"
    replace: "account"

  - trigger: "yym"
    replace: "yapp-mobile"

  - trigger: "yym"
    replace: "mobile-ui"

  - trigger: "yyek"
    replace: "yapp-ember-kit"

