#!/bin/sh

log() {
  echo ""
  echo " ==> $1"
  echo ""
}

[ ! -d ~/.tmux/plugins/tpm ] && (
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
)

[ ! -d ~/.vim/autoload ] && (
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim -c 'PlugUpdate'
)

if grep -q '^TAGS=.*\bpython\b' ~/.rcrc; then
  [ ! -d $HOME/.pyenv/versions ] && (
    log "Installing system python version"
    pyenv install -s `~/.python-version`
  )
fi

if grep -q '^TAGS=.*\bruby\b' ~/.rcrc; then
  [ ! -d $HOME/.rbenv ] && (
    log "Installing system ruby version"
    rbenv install -s `~/.ruby-version`
  )

  [[ ! $(which bundler) ]] && (
    log "Configuring ruby environment"
    gem update --system
    gem install bundler --no-document --pre
    number_of_cores=$(sysctl -n hw.ncpu)
    bundle config --global jobs $((number_of_cores - 1))
  )
fi